#%RAML 1.0
title: HelthRoutine API
version: v1
baseUri: http://127.0.0.1:8000/
protocols:
  - HTTP
mediaType:
  - application/json
types:
  # Object used for request/response
  content:
    type: object
    properties:
      id:
        type: integer
        required: Auto
      title:
        type: string
        required: False
      routine:
        type: string
        required: True
      sets:
        type: string  
        required: True
      count:
        type: string  
        required: True
      created_at:
        type: datetime
        required: Auto
      updated_at:
        type: datetime
        required: Auto

  # Object used for error
  error:
    type: object
    properties:
      message:
        type: string
        required: true
/content:
  displayName: Content
  description: |
  get:
    description: |
      # Get
    responses:
      200:
        body:
          type: contents[]
          # Sample response
          example:
            -
              id : 1
              title: : test title 1
              routine : 스쿼트, 윗몸일으키기
              sets: 2, 3
              count: 10, 5
              created_at : 2020-07-12 17:59:50
              updated_at : 2020-07-12 18:00:15
  /{contentId}:
    displayName: Content
    description: |
    uriParameters:
      contentId:
        type: integer
    patch:
      description: |
      responses:
        201:
          body:
            type: contents[]
            # Sample response
            example:
              id : 1
              title: : test title 1
              routine : 스쿼트,윗몸일으키기
              sets: 2,3
              count: 10,5
              created_at : 2020-07-12 17:59:50
              updated_at : 2020-07-12 18:00:15
        404:
          body:
            type: error
            # Sample response
            example:
              message: Not Found
    delete:
      description: |
      responses:
        204:
          body:
        404:
          body:
            type: error
            # Sample response
            example:
              message: Not Found     
  /create:
    displayName: Content
    description: |
    get:
      description: |
      # Get
      responses:
        204:
          body:
        404:
          body: 
            type: error
          example:
            message: Not Found
    post:
      body:
        type: contents[]
      responses:
        # Sample response
        201:
          body:
            type: contents[]
            example:
                id : 1
                title: : test title 1
                routine : ""
                created_at : '2020-07-12 17:59:50'
                updated_at : '2020-07-12 18:00:15'
        404:
          body: 
            type: error
          example:
            message: Not Found

login:
  /login:
    get:
    post:

user:
  /user:
    displayName: user
    description: |
    get:
      description: |
      responses:
        200:
          body:
            type: user[]
            example:
              id : 1
              email : 1234@1234.com
              password : 123456789
              is_actived : True

    patch:
    /content:
      get:

signup:
  /signup:
    get:
    post:

email:
  /email/{token}/verify/{user}:
    get:

search:
  /search:
    get:
    /{keyword}:
      get:

home:
  /home:
    get:
