# Generated by Django 3.1 on 2020-09-16 14:56

from django.db import migrations
import login_system.models


class Migration(migrations.Migration):

    dependencies = [
        ('login_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', login_system.models.UserManager()),
            ],
        ),
    ]
