# Generated by Django 3.1.1 on 2020-09-12 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_system', '0002_auto_20200911_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.CharField(max_length=70),
        ),
    ]
