# Generated by Django 3.1.1 on 2020-09-12 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_system', '0003_auto_20200912_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(max_length=70),
        ),
    ]
