# Generated by Django 3.0.5 on 2020-07-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, verbose_name='제목')),
                ('sports_name', models.CharField(max_length=100, verbose_name='운동 이름')),
                ('routine', models.IntegerField(default=0, verbose_name='루틴')),
                ('sets', models.IntegerField(default=0, verbose_name='세트')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='생성 날짜')),
                ('updated_date', models.DateTimeField(auto_now_add=True, verbose_name='수정 날짜')),
            ],
        ),
    ]
