# Generated by Django 3.0.5 on 2020-07-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='routine',
            field=models.CharField(max_length=50, verbose_name='루틴'),
        ),
        migrations.AlterField(
            model_name='post',
            name='sets',
            field=models.CharField(max_length=50, verbose_name='세트'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=30, verbose_name='제목'),
        ),
    ]
